spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:solabo123@cluster0.vdwax.mongodb.net/?retryWrites=true&w=majority
      database: sm

debug: true
logging:
  level:
    org:
      springframework:
        context: DEBUG
        boot:
          autoconfigure: ERROR
#      host: localhost
#      port: 27017
#      database: sm